### ISSUE TITLE
Ciclos

### ISSUE THREAD

**Issue by IngridChs** [elgui02/horarios#1]
Para poder establecer los ciclos de cada carrera, no estan visibles en el menu de administracion

**Comment by elgui02** [comment]
Los ciclos? podrías detallar más sobre que es?

**Comment by IngridChs** [comment]
los semestres que corresponden a cada curso no estan, para poder hacer los cursos y visualizarlos por semestre o ciclo de cada carrera

**Comment by elgui02** [comment]
Eso ya esta, es configurable por carrera
